### ISSUE TITLE
Difference between nuget and this version

### ISSUE THREAD

**Issue by arc95** [rsevil/Transactions#2]
Thanks, @rsevil, for this great library. I used nuget package manager to install the package and discovered that `WriteAllBytes` was missing, while the github version has it. I'm using the github version and quite happy with it. Any reason for the difference? The one in package manager is this one:

![image](https://user-images.githubusercontent.com/2144909/50691275-38c42800-0ffe-11e9-85ca-51326e5b534d.png)

And it seems to be the same one that's here: https://www.nuget.org/packages/TxFileManager/

**Comment by rsevil** [comment]
Hi @arc95, it's been a while since I'm not actively maintaining this library, so I searched over the commit history but I don't remember why I added or removed the `WriteAllBytes` method, but it seems that it wasn't implemented over the original lib.

As for the nuget package, did you downloaded the package over of the following url?
- https://www.nuget.org/packages/ChinhDo.Transactions.FileManager/

**Comment by arc95** [comment]
Thanks, @rsevil. No, I downloaded it from here: https://www.nuget.org/packages/TxFileManager/
Didn't realize the package was actually on the link you provided.
